
services:
  backend-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: dev-deps
    container_name: boardly-backend-dev
    ports:
      - "3001:3000"
    volumes:
      - ../backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
      - ../backend/package.json:/usr/src/app/package.json
      - ../backend/package-lock.json:/usr/src/app/package-lock.json
    command: sh -c "npm ci && npm run start:dev"
    environment:
      - NODE_ENV=development
    networks:
      - boardly-network

  frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: dev-deps
    container_name: boardly-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
      - ../frontend/package.json:/app/package.json
      - ../frontend/package-lock.json:/app/package-lock.json
    command: sh -c "npm ci && npm run dev"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    networks:
      - boardly-network
    depends_on:
      - backend-dev

volumes:
  frontend_node_modules:
  backend_node_modules:

networks:
  boardly-network:
    driver: bridge